export declare type ValidatorFn<T = any> = (fieldValue: T) => string | null;
declare type ValidatorFactory<T = unknown> = (message: string, config?: T) => ValidatorFn;
export declare const required: ValidatorFactory;
export declare const email: ValidatorFactory;
export declare const minLength: ValidatorFactory<number>;
export declare const maxLength: ValidatorFactory<number>;
export declare const number: ValidatorFactory;
export declare const decimal: ValidatorFactory;
export declare const integer: ValidatorFactory;
export declare const min: ValidatorFactory<number>;
export declare const max: ValidatorFactory<number>;
export declare const pattern: ValidatorFactory<RegExp>;
export {};
